version: "3"

services:
  aapanel:
    build:
      context: ./docker-file
    container_name: "aapanel-webserver"
    restart: unless-stopped
    ports:
      - "${AAPANEL_PORT}:7800"
      - "${WEBSERVER_HOST_PORT}:80"
      - "${WEBSERVER_SECURE_HOST_PORT}:443"
      - "${PHPMYADMIN_PORT}:888"
      - "${REDIS_PORT}:6379"
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${WEBSITE_DATA}:/www/wwwroot
      - ${WEBSITE_MYSQL}:/www/server/data
      - ${WEBSITE_PANEL}:/www/server/panel/data
      - ${WEBSITE_VHOST}:/www/server/panel/vhost
      - ${WEBSITE_BACKUP}:/www/backup
      - ${WEBSITE_LOG}:/www/wwwlogs
    env_file:
      - ./.env
